---
- include_tasks:
    file: check_vars.yml
    apply:
      tags:
        - check
        - varnish
  tags:
    - always

- include_tasks:
    file: varnish.yml
    apply:
      tags:
        - varnish
  tags:
    - always
